# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../resources/ui/add_fictionbook.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_AddFictionbookWindow(object):
    def setupUi(self, AddFictionbookWindow):
        AddFictionbookWindow.setObjectName("AddFictionbookWindow")
        AddFictionbookWindow.resize(400, 470)
        AddFictionbookWindow.setMinimumSize(QtCore.QSize(400, 470))
        AddFictionbookWindow.setMaximumSize(QtCore.QSize(400, 470))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/icons/logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        AddFictionbookWindow.setWindowIcon(icon)
        AddFictionbookWindow.setStyleSheet("background-color: rgb(233, 185, 110);")
        self.gridLayout = QtWidgets.QGridLayout(AddFictionbookWindow)
        self.gridLayout.setObjectName("gridLayout")
        self.addFictionbookGroupBox = QtWidgets.QGroupBox(AddFictionbookWindow)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.addFictionbookGroupBox.setFont(font)
        self.addFictionbookGroupBox.setStyleSheet("\n"
"\n"
"QGroupBox {\n"
"    border: 1px solid gray;\n"
"    border-radius: 9px;\n"
"    margin-top: 0.5em;\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    left: 10px;\n"
"    padding: 0 3px 0 3px;\n"
"}\n"
"\n"
"")
        self.addFictionbookGroupBox.setFlat(False)
        self.addFictionbookGroupBox.setObjectName("addFictionbookGroupBox")
        self.formLayoutWidget = QtWidgets.QWidget(self.addFictionbookGroupBox)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 30, 361, 314))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.addFictionbookForm = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.addFictionbookForm.setContentsMargins(0, 0, 0, 0)
        self.addFictionbookForm.setObjectName("addFictionbookForm")
        self.authorLabel = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.authorLabel.setFont(font)
        self.authorLabel.setStyleSheet("color: rgb(117, 94, 59);")
        self.authorLabel.setObjectName("authorLabel")
        self.addFictionbookForm.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.authorLabel)
        self.fictionbookAuthor = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.fictionbookAuthor.setMinimumSize(QtCore.QSize(0, 25))
        self.fictionbookAuthor.setMaximumSize(QtCore.QSize(16777215, 25))
        self.fictionbookAuthor.setStyleSheet("background-color: rgb(244, 217, 173);")
        self.fictionbookAuthor.setObjectName("fictionbookAuthor")
        self.addFictionbookForm.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.fictionbookAuthor)
        self.titleLabel = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.titleLabel.setFont(font)
        self.titleLabel.setStyleSheet("color: rgb(117, 94, 59);")
        self.titleLabel.setObjectName("titleLabel")
        self.addFictionbookForm.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.titleLabel)
        self.fictionbookTitle = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.fictionbookTitle.setMinimumSize(QtCore.QSize(0, 25))
        self.fictionbookTitle.setMaximumSize(QtCore.QSize(16777215, 25))
        self.fictionbookTitle.setStyleSheet("background-color: rgb(244, 217, 173);")
        self.fictionbookTitle.setObjectName("fictionbookTitle")
        self.addFictionbookForm.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.fictionbookTitle)
        self.publishHouseLabel = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.publishHouseLabel.setFont(font)
        self.publishHouseLabel.setStyleSheet("color: rgb(117, 94, 59);")
        self.publishHouseLabel.setObjectName("publishHouseLabel")
        self.addFictionbookForm.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.publishHouseLabel)
        self.fictionbookPublishHouse = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.fictionbookPublishHouse.setMinimumSize(QtCore.QSize(0, 25))
        self.fictionbookPublishHouse.setMaximumSize(QtCore.QSize(16777215, 25))
        self.fictionbookPublishHouse.setStyleSheet("background-color: rgb(244, 217, 173);")
        self.fictionbookPublishHouse.setObjectName("fictionbookPublishHouse")
        self.addFictionbookForm.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.fictionbookPublishHouse)
        self.publishYearLabel = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.publishYearLabel.setFont(font)
        self.publishYearLabel.setStyleSheet("color: rgb(117, 94, 59);")
        self.publishYearLabel.setObjectName("publishYearLabel")
        self.addFictionbookForm.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.publishYearLabel)
        self.fictionbookPublishYear = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.fictionbookPublishYear.setMinimumSize(QtCore.QSize(0, 25))
        self.fictionbookPublishYear.setMaximumSize(QtCore.QSize(16777215, 25))
        self.fictionbookPublishYear.setStyleSheet("background-color: rgb(244, 217, 173);")
        self.fictionbookPublishYear.setObjectName("fictionbookPublishYear")
        self.addFictionbookForm.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.fictionbookPublishYear)
        self.inventoryNumberLabel = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.inventoryNumberLabel.setFont(font)
        self.inventoryNumberLabel.setStyleSheet("color: rgb(117, 94, 59);")
        self.inventoryNumberLabel.setObjectName("inventoryNumberLabel")
        self.addFictionbookForm.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.inventoryNumberLabel)
        self.fictionbookInventoryNumber = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.fictionbookInventoryNumber.setMinimumSize(QtCore.QSize(0, 25))
        self.fictionbookInventoryNumber.setMaximumSize(QtCore.QSize(16777215, 25))
        self.fictionbookInventoryNumber.setStyleSheet("background-color: rgb(244, 217, 173);")
        self.fictionbookInventoryNumber.setObjectName("fictionbookInventoryNumber")
        self.addFictionbookForm.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.fictionbookInventoryNumber)
        self.countLabel = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.countLabel.setFont(font)
        self.countLabel.setStyleSheet("color: rgb(117, 94, 59);")
        self.countLabel.setObjectName("countLabel")
        self.addFictionbookForm.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.countLabel)
        self.fictionbookCount = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.fictionbookCount.setMinimumSize(QtCore.QSize(0, 25))
        self.fictionbookCount.setMaximumSize(QtCore.QSize(16777215, 25))
        self.fictionbookCount.setStyleSheet("background-color: rgb(244, 217, 173);")
        self.fictionbookCount.setObjectName("fictionbookCount")
        self.addFictionbookForm.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.fictionbookCount)
        self.priceLabel = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.priceLabel.setFont(font)
        self.priceLabel.setStyleSheet("color: rgb(117, 94, 59);")
        self.priceLabel.setObjectName("priceLabel")
        self.addFictionbookForm.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.priceLabel)
        self.fictionbookPrice = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.fictionbookPrice.setMinimumSize(QtCore.QSize(0, 25))
        self.fictionbookPrice.setMaximumSize(QtCore.QSize(16777215, 25))
        self.fictionbookPrice.setStyleSheet("background-color: rgb(244, 217, 173);")
        self.fictionbookPrice.setObjectName("fictionbookPrice")
        self.addFictionbookForm.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.fictionbookPrice)
        self.invoiceNumLabel = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.invoiceNumLabel.setFont(font)
        self.invoiceNumLabel.setStyleSheet("color: rgb(117, 94, 59);")
        self.invoiceNumLabel.setObjectName("invoiceNumLabel")
        self.addFictionbookForm.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.invoiceNumLabel)
        self.fictionbookInvoiceNum = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.fictionbookInvoiceNum.setMinimumSize(QtCore.QSize(0, 25))
        self.fictionbookInvoiceNum.setMaximumSize(QtCore.QSize(16777215, 25))
        self.fictionbookInvoiceNum.setStyleSheet("background-color: rgb(244, 217, 173);")
        self.fictionbookInvoiceNum.setObjectName("fictionbookInvoiceNum")
        self.addFictionbookForm.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.fictionbookInvoiceNum)
        self.invoiceDateLabel = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.invoiceDateLabel.setFont(font)
        self.invoiceDateLabel.setStyleSheet("color: rgb(117, 94, 59);")
        self.invoiceDateLabel.setObjectName("invoiceDateLabel")
        self.addFictionbookForm.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.invoiceDateLabel)
        self.fictionbookInvoiceDate = QtWidgets.QDateEdit(self.formLayoutWidget)
        self.fictionbookInvoiceDate.setMinimumSize(QtCore.QSize(0, 25))
        self.fictionbookInvoiceDate.setMaximumSize(QtCore.QSize(16777215, 25))
        self.fictionbookInvoiceDate.setStyleSheet("background-color: rgb(244, 217, 173);")
        self.fictionbookInvoiceDate.setDate(QtCore.QDate(1900, 12, 31))
        self.fictionbookInvoiceDate.setObjectName("fictionbookInvoiceDate")
        self.addFictionbookForm.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.fictionbookInvoiceDate)
        self.departmentLabel = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.departmentLabel.setFont(font)
        self.departmentLabel.setStyleSheet("color: rgb(117, 94, 59);")
        self.departmentLabel.setObjectName("departmentLabel")
        self.addFictionbookForm.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.departmentLabel)
        self.fictionbookDepartment = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.fictionbookDepartment.setMinimumSize(QtCore.QSize(0, 25))
        self.fictionbookDepartment.setMaximumSize(QtCore.QSize(16777215, 25))
        self.fictionbookDepartment.setStyleSheet("background-color: rgb(244, 217, 173);")
        self.fictionbookDepartment.setObjectName("fictionbookDepartment")
        self.addFictionbookForm.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.fictionbookDepartment)
        self.gridLayout.addWidget(self.addFictionbookGroupBox, 0, 0, 1, 1)
        self.fictionbookSaveBtn = QtWidgets.QPushButton(AddFictionbookWindow)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.fictionbookSaveBtn.setFont(font)
        self.fictionbookSaveBtn.setStyleSheet("background-color: rgb(117, 94, 59);\n"
"color: rgb(255, 255, 255);")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icon/icons/saveBtnIcon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.fictionbookSaveBtn.setIcon(icon1)
        self.fictionbookSaveBtn.setCheckable(False)
        self.fictionbookSaveBtn.setObjectName("fictionbookSaveBtn")
        self.gridLayout.addWidget(self.fictionbookSaveBtn, 1, 0, 1, 1)
        self.fictionbookClearBtn = QtWidgets.QPushButton(AddFictionbookWindow)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.fictionbookClearBtn.setFont(font)
        self.fictionbookClearBtn.setStyleSheet("background-color: rgb(117, 94, 59);\n"
"color: rgb(255, 255, 255);")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icon/icons/clearBtnIcon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.fictionbookClearBtn.setIcon(icon2)
        self.fictionbookClearBtn.setObjectName("fictionbookClearBtn")
        self.gridLayout.addWidget(self.fictionbookClearBtn, 2, 0, 1, 1)
        self.fictionbookCancelBtn = QtWidgets.QPushButton(AddFictionbookWindow)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.fictionbookCancelBtn.setFont(font)
        self.fictionbookCancelBtn.setStyleSheet("background-color: rgb(117, 94, 59);\n"
"color: rgb(255, 255, 255);")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icon/icons/cancelBtnIcon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.fictionbookCancelBtn.setIcon(icon3)
        self.fictionbookCancelBtn.setObjectName("fictionbookCancelBtn")
        self.gridLayout.addWidget(self.fictionbookCancelBtn, 3, 0, 1, 1)

        self.retranslateUi(AddFictionbookWindow)
        QtCore.QMetaObject.connectSlotsByName(AddFictionbookWindow)
        AddFictionbookWindow.setTabOrder(self.fictionbookAuthor, self.fictionbookTitle)
        AddFictionbookWindow.setTabOrder(self.fictionbookTitle, self.fictionbookPublishHouse)
        AddFictionbookWindow.setTabOrder(self.fictionbookPublishHouse, self.fictionbookPublishYear)
        AddFictionbookWindow.setTabOrder(self.fictionbookPublishYear, self.fictionbookCount)
        AddFictionbookWindow.setTabOrder(self.fictionbookCount, self.fictionbookPrice)
        AddFictionbookWindow.setTabOrder(self.fictionbookPrice, self.fictionbookInvoiceNum)

    def retranslateUi(self, AddFictionbookWindow):
        _translate = QtCore.QCoreApplication.translate
        AddFictionbookWindow.setWindowTitle(_translate("AddFictionbookWindow", "Добавить художественную книгу"))
        self.addFictionbookGroupBox.setTitle(_translate("AddFictionbookWindow", "Добавить художественную книгу"))
        self.authorLabel.setText(_translate("AddFictionbookWindow", "Автор:"))
        self.titleLabel.setText(_translate("AddFictionbookWindow", "Название:"))
        self.publishHouseLabel.setText(_translate("AddFictionbookWindow", "Издательство:"))
        self.publishYearLabel.setText(_translate("AddFictionbookWindow", "Год издания:"))
        self.inventoryNumberLabel.setText(_translate("AddFictionbookWindow", "Инвентарный номер:"))
        self.countLabel.setText(_translate("AddFictionbookWindow", "Количество:"))
        self.priceLabel.setText(_translate("AddFictionbookWindow", "Цена:"))
        self.invoiceNumLabel.setText(_translate("AddFictionbookWindow", "№ накладной:"))
        self.invoiceDateLabel.setText(_translate("AddFictionbookWindow", "Дата накладной:"))
        self.fictionbookInvoiceDate.setDisplayFormat(_translate("AddFictionbookWindow", "dd.MM.yyyy"))
        self.departmentLabel.setText(_translate("AddFictionbookWindow", "Отдел:"))
        self.fictionbookSaveBtn.setText(_translate("AddFictionbookWindow", "Сохранить"))
        self.fictionbookClearBtn.setText(_translate("AddFictionbookWindow", "Сброс"))
        self.fictionbookCancelBtn.setText(_translate("AddFictionbookWindow", "Отмена"))

import package.views.images_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AddFictionbookWindow = QtWidgets.QDialog()
    ui = Ui_AddFictionbookWindow()
    ui.setupUi(AddFictionbookWindow)
    AddFictionbookWindow.show()
    sys.exit(app.exec_())

