# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../resources/ui/search_schoolbook.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_SearchSchoolbookWindow(object):
    def setupUi(self, SearchSchoolbookWindow):
        SearchSchoolbookWindow.setObjectName("SearchSchoolbookWindow")
        SearchSchoolbookWindow.resize(400, 460)
        SearchSchoolbookWindow.setMinimumSize(QtCore.QSize(400, 460))
        SearchSchoolbookWindow.setMaximumSize(QtCore.QSize(400, 460))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/icons/logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        SearchSchoolbookWindow.setWindowIcon(icon)
        SearchSchoolbookWindow.setStyleSheet("background-color: rgb(233, 185, 110);")
        self.gridLayout = QtWidgets.QGridLayout(SearchSchoolbookWindow)
        self.gridLayout.setObjectName("gridLayout")
        self.SearchSchoolbookGroupBox = QtWidgets.QGroupBox(SearchSchoolbookWindow)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.SearchSchoolbookGroupBox.setFont(font)
        self.SearchSchoolbookGroupBox.setStyleSheet("\n"
"\n"
"QGroupBox {\n"
"    border: 1px solid gray;\n"
"    border-radius: 9px;\n"
"    margin-top: 0.5em;\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    left: 10px;\n"
"    padding: 0 3px 0 3px;\n"
"}\n"
"\n"
"")
        self.SearchSchoolbookGroupBox.setFlat(False)
        self.SearchSchoolbookGroupBox.setObjectName("SearchSchoolbookGroupBox")
        self.formLayoutWidget = QtWidgets.QWidget(self.SearchSchoolbookGroupBox)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 30, 361, 314))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.searchSchoolbookForm = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.searchSchoolbookForm.setContentsMargins(0, 0, 0, 0)
        self.searchSchoolbookForm.setObjectName("searchSchoolbookForm")
        self.authorLabel = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.authorLabel.setFont(font)
        self.authorLabel.setStyleSheet("color: rgb(117, 94, 59);")
        self.authorLabel.setObjectName("authorLabel")
        self.searchSchoolbookForm.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.authorLabel)
        self.schoolbookAuthor = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.schoolbookAuthor.setMinimumSize(QtCore.QSize(0, 25))
        self.schoolbookAuthor.setMaximumSize(QtCore.QSize(16777215, 25))
        self.schoolbookAuthor.setStyleSheet("background-color: rgb(244, 217, 173);")
        self.schoolbookAuthor.setObjectName("schoolbookAuthor")
        self.searchSchoolbookForm.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.schoolbookAuthor)
        self.titleLabel = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.titleLabel.setFont(font)
        self.titleLabel.setStyleSheet("color: rgb(117, 94, 59);")
        self.titleLabel.setObjectName("titleLabel")
        self.searchSchoolbookForm.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.titleLabel)
        self.schoolbookTitle = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.schoolbookTitle.setMinimumSize(QtCore.QSize(0, 25))
        self.schoolbookTitle.setMaximumSize(QtCore.QSize(16777215, 25))
        self.schoolbookTitle.setStyleSheet("background-color: rgb(244, 217, 173);")
        self.schoolbookTitle.setObjectName("schoolbookTitle")
        self.searchSchoolbookForm.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.schoolbookTitle)
        self.publishHouseLabel = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.publishHouseLabel.setFont(font)
        self.publishHouseLabel.setStyleSheet("color: rgb(117, 94, 59);")
        self.publishHouseLabel.setObjectName("publishHouseLabel")
        self.searchSchoolbookForm.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.publishHouseLabel)
        self.schoolbookPublishHouse = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.schoolbookPublishHouse.setMinimumSize(QtCore.QSize(0, 25))
        self.schoolbookPublishHouse.setMaximumSize(QtCore.QSize(16777215, 25))
        self.schoolbookPublishHouse.setStyleSheet("background-color: rgb(244, 217, 173);")
        self.schoolbookPublishHouse.setObjectName("schoolbookPublishHouse")
        self.searchSchoolbookForm.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.schoolbookPublishHouse)
        self.publishYearLabel = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.publishYearLabel.setFont(font)
        self.publishYearLabel.setStyleSheet("color: rgb(117, 94, 59);")
        self.publishYearLabel.setObjectName("publishYearLabel")
        self.searchSchoolbookForm.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.publishYearLabel)
        self.schoolbookPublishYear = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.schoolbookPublishYear.setMinimumSize(QtCore.QSize(0, 25))
        self.schoolbookPublishYear.setMaximumSize(QtCore.QSize(16777215, 25))
        self.schoolbookPublishYear.setStyleSheet("background-color: rgb(244, 217, 173);")
        self.schoolbookPublishYear.setObjectName("schoolbookPublishYear")
        self.searchSchoolbookForm.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.schoolbookPublishYear)
        self.classLabel = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.classLabel.setFont(font)
        self.classLabel.setStyleSheet("color: rgb(117, 94, 59);")
        self.classLabel.setObjectName("classLabel")
        self.searchSchoolbookForm.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.classLabel)
        self.schoolbookClass = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.schoolbookClass.setMinimumSize(QtCore.QSize(0, 25))
        self.schoolbookClass.setMaximumSize(QtCore.QSize(16777215, 25))
        self.schoolbookClass.setStyleSheet("background-color: rgb(244, 217, 173);")
        self.schoolbookClass.setObjectName("schoolbookClass")
        self.searchSchoolbookForm.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.schoolbookClass)
        self.countLabel = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.countLabel.setFont(font)
        self.countLabel.setStyleSheet("color: rgb(117, 94, 59);")
        self.countLabel.setObjectName("countLabel")
        self.searchSchoolbookForm.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.countLabel)
        self.schoolbookCount = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.schoolbookCount.setMinimumSize(QtCore.QSize(0, 25))
        self.schoolbookCount.setMaximumSize(QtCore.QSize(16777215, 25))
        self.schoolbookCount.setStyleSheet("background-color: rgb(244, 217, 173);")
        self.schoolbookCount.setObjectName("schoolbookCount")
        self.searchSchoolbookForm.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.schoolbookCount)
        self.priceLabel = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.priceLabel.setFont(font)
        self.priceLabel.setStyleSheet("color: rgb(117, 94, 59);")
        self.priceLabel.setObjectName("priceLabel")
        self.searchSchoolbookForm.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.priceLabel)
        self.schoolbookPrice = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.schoolbookPrice.setMinimumSize(QtCore.QSize(0, 25))
        self.schoolbookPrice.setMaximumSize(QtCore.QSize(16777215, 25))
        self.schoolbookPrice.setStyleSheet("background-color: rgb(244, 217, 173);")
        self.schoolbookPrice.setObjectName("schoolbookPrice")
        self.searchSchoolbookForm.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.schoolbookPrice)
        self.invoiceNumLabel = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.invoiceNumLabel.setFont(font)
        self.invoiceNumLabel.setStyleSheet("color: rgb(117, 94, 59);")
        self.invoiceNumLabel.setObjectName("invoiceNumLabel")
        self.searchSchoolbookForm.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.invoiceNumLabel)
        self.schoolbookInvoiceNum = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.schoolbookInvoiceNum.setMinimumSize(QtCore.QSize(0, 25))
        self.schoolbookInvoiceNum.setMaximumSize(QtCore.QSize(16777215, 25))
        self.schoolbookInvoiceNum.setStyleSheet("background-color: rgb(244, 217, 173);")
        self.schoolbookInvoiceNum.setObjectName("schoolbookInvoiceNum")
        self.searchSchoolbookForm.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.schoolbookInvoiceNum)
        self.invoiceDateLabel = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.invoiceDateLabel.setFont(font)
        self.invoiceDateLabel.setStyleSheet("color: rgb(117, 94, 59);")
        self.invoiceDateLabel.setObjectName("invoiceDateLabel")
        self.searchSchoolbookForm.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.invoiceDateLabel)
        self.schoolbookInvoiceDate = QtWidgets.QDateEdit(self.formLayoutWidget)
        self.schoolbookInvoiceDate.setMinimumSize(QtCore.QSize(0, 25))
        self.schoolbookInvoiceDate.setMaximumSize(QtCore.QSize(16777215, 25))
        self.schoolbookInvoiceDate.setStyleSheet("background-color: rgb(244, 217, 173);")
        self.schoolbookInvoiceDate.setDate(QtCore.QDate(1900, 12, 31))
        self.schoolbookInvoiceDate.setObjectName("schoolbookInvoiceDate")
        self.searchSchoolbookForm.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.schoolbookInvoiceDate)
        self.sumLabel = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.sumLabel.setFont(font)
        self.sumLabel.setStyleSheet("color: rgb(117, 94, 59);")
        self.sumLabel.setObjectName("sumLabel")
        self.searchSchoolbookForm.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.sumLabel)
        self.schoolbookSum = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.schoolbookSum.setMinimumSize(QtCore.QSize(0, 25))
        self.schoolbookSum.setMaximumSize(QtCore.QSize(16777215, 25))
        self.schoolbookSum.setStyleSheet("background-color: rgb(244, 217, 173);")
        self.schoolbookSum.setObjectName("schoolbookSum")
        self.searchSchoolbookForm.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.schoolbookSum)
        self.gridLayout.addWidget(self.SearchSchoolbookGroupBox, 0, 0, 1, 1)
        self.schoolbookSearchBtn = QtWidgets.QPushButton(SearchSchoolbookWindow)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.schoolbookSearchBtn.setFont(font)
        self.schoolbookSearchBtn.setStyleSheet("background-color: rgb(117, 94, 59);\n"
"color: rgb(255, 255, 255);")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icon/icons/searchBtnIcon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.schoolbookSearchBtn.setIcon(icon1)
        self.schoolbookSearchBtn.setCheckable(False)
        self.schoolbookSearchBtn.setObjectName("schoolbookSearchBtn")
        self.gridLayout.addWidget(self.schoolbookSearchBtn, 1, 0, 1, 1)
        self.schoolbookClearBtn = QtWidgets.QPushButton(SearchSchoolbookWindow)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.schoolbookClearBtn.setFont(font)
        self.schoolbookClearBtn.setStyleSheet("background-color: rgb(117, 94, 59);\n"
"color: rgb(255, 255, 255);")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icon/icons/clearBtnIcon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.schoolbookClearBtn.setIcon(icon2)
        self.schoolbookClearBtn.setObjectName("schoolbookClearBtn")
        self.gridLayout.addWidget(self.schoolbookClearBtn, 2, 0, 1, 1)
        self.schoolbookCancelBtn = QtWidgets.QPushButton(SearchSchoolbookWindow)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.schoolbookCancelBtn.setFont(font)
        self.schoolbookCancelBtn.setStyleSheet("background-color: rgb(117, 94, 59);\n"
"color: rgb(255, 255, 255);")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icon/icons/cancelBtnIcon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.schoolbookCancelBtn.setIcon(icon3)
        self.schoolbookCancelBtn.setObjectName("schoolbookCancelBtn")
        self.gridLayout.addWidget(self.schoolbookCancelBtn, 3, 0, 1, 1)

        self.retranslateUi(SearchSchoolbookWindow)
        QtCore.QMetaObject.connectSlotsByName(SearchSchoolbookWindow)
        SearchSchoolbookWindow.setTabOrder(self.schoolbookAuthor, self.schoolbookTitle)
        SearchSchoolbookWindow.setTabOrder(self.schoolbookTitle, self.schoolbookPublishHouse)
        SearchSchoolbookWindow.setTabOrder(self.schoolbookPublishHouse, self.schoolbookPublishYear)
        SearchSchoolbookWindow.setTabOrder(self.schoolbookPublishYear, self.schoolbookCount)
        SearchSchoolbookWindow.setTabOrder(self.schoolbookCount, self.schoolbookPrice)
        SearchSchoolbookWindow.setTabOrder(self.schoolbookPrice, self.schoolbookInvoiceNum)

    def retranslateUi(self, SearchSchoolbookWindow):
        _translate = QtCore.QCoreApplication.translate
        SearchSchoolbookWindow.setWindowTitle(_translate("SearchSchoolbookWindow", "Поиск учебника"))
        self.SearchSchoolbookGroupBox.setTitle(_translate("SearchSchoolbookWindow", "Найти учебник"))
        self.authorLabel.setText(_translate("SearchSchoolbookWindow", "Автор:"))
        self.titleLabel.setText(_translate("SearchSchoolbookWindow", "Название:"))
        self.publishHouseLabel.setText(_translate("SearchSchoolbookWindow", "Издательство:"))
        self.publishYearLabel.setText(_translate("SearchSchoolbookWindow", "Год издания:"))
        self.classLabel.setText(_translate("SearchSchoolbookWindow", "Класс:"))
        self.countLabel.setText(_translate("SearchSchoolbookWindow", "Количество:"))
        self.priceLabel.setText(_translate("SearchSchoolbookWindow", "Цена:"))
        self.invoiceNumLabel.setText(_translate("SearchSchoolbookWindow", "№ накладной:"))
        self.invoiceDateLabel.setText(_translate("SearchSchoolbookWindow", "Дата накладной"))
        self.schoolbookInvoiceDate.setDisplayFormat(_translate("SearchSchoolbookWindow", "dd.MM.yyyy"))
        self.sumLabel.setText(_translate("SearchSchoolbookWindow", "Сумма:"))
        self.schoolbookSearchBtn.setText(_translate("SearchSchoolbookWindow", "Найти"))
        self.schoolbookClearBtn.setText(_translate("SearchSchoolbookWindow", "Сбросить"))
        self.schoolbookCancelBtn.setText(_translate("SearchSchoolbookWindow", "Отмена"))

import package.views.images_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SearchSchoolbookWindow = QtWidgets.QDialog()
    ui = Ui_SearchSchoolbookWindow()
    ui.setupUi(SearchSchoolbookWindow)
    SearchSchoolbookWindow.show()
    sys.exit(app.exec_())

