# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../resources/ui/search_fictionbook.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_SearchFictionbookWindow(object):
    def setupUi(self, SearchFictionbookWindow):
        SearchFictionbookWindow.setObjectName("SearchFictionbookWindow")
        SearchFictionbookWindow.resize(400, 490)
        SearchFictionbookWindow.setMinimumSize(QtCore.QSize(400, 490))
        SearchFictionbookWindow.setMaximumSize(QtCore.QSize(400, 460))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/icons/logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        SearchFictionbookWindow.setWindowIcon(icon)
        SearchFictionbookWindow.setStyleSheet("background-color: rgb(233, 185, 110);")
        self.gridLayout = QtWidgets.QGridLayout(SearchFictionbookWindow)
        self.gridLayout.setObjectName("gridLayout")
        self.SearchFictionbookGroupBox = QtWidgets.QGroupBox(SearchFictionbookWindow)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.SearchFictionbookGroupBox.setFont(font)
        self.SearchFictionbookGroupBox.setStyleSheet("\n"
"\n"
"QGroupBox {\n"
"    border: 1px solid gray;\n"
"    border-radius: 9px;\n"
"    margin-top: 0.5em;\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    left: 10px;\n"
"    padding: 0 3px 0 3px;\n"
"}\n"
"\n"
"")
        self.SearchFictionbookGroupBox.setFlat(False)
        self.SearchFictionbookGroupBox.setObjectName("SearchFictionbookGroupBox")
        self.formLayoutWidget = QtWidgets.QWidget(self.SearchFictionbookGroupBox)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 30, 361, 345))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.searchFictionbookForm = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.searchFictionbookForm.setContentsMargins(0, 0, 0, 0)
        self.searchFictionbookForm.setObjectName("searchFictionbookForm")
        self.authorLabel = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.authorLabel.setFont(font)
        self.authorLabel.setStyleSheet("color: rgb(117, 94, 59);")
        self.authorLabel.setObjectName("authorLabel")
        self.searchFictionbookForm.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.authorLabel)
        self.fictionbookAuthor = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.fictionbookAuthor.setMinimumSize(QtCore.QSize(0, 25))
        self.fictionbookAuthor.setMaximumSize(QtCore.QSize(16777215, 25))
        self.fictionbookAuthor.setStyleSheet("background-color: rgb(244, 217, 173);")
        self.fictionbookAuthor.setObjectName("fictionbookAuthor")
        self.searchFictionbookForm.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.fictionbookAuthor)
        self.titleLabel = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.titleLabel.setFont(font)
        self.titleLabel.setStyleSheet("color: rgb(117, 94, 59);")
        self.titleLabel.setObjectName("titleLabel")
        self.searchFictionbookForm.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.titleLabel)
        self.fictionbookTitle = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.fictionbookTitle.setMinimumSize(QtCore.QSize(0, 25))
        self.fictionbookTitle.setMaximumSize(QtCore.QSize(16777215, 25))
        self.fictionbookTitle.setStyleSheet("background-color: rgb(244, 217, 173);")
        self.fictionbookTitle.setObjectName("fictionbookTitle")
        self.searchFictionbookForm.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.fictionbookTitle)
        self.publishHouseLabel = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.publishHouseLabel.setFont(font)
        self.publishHouseLabel.setStyleSheet("color: rgb(117, 94, 59);")
        self.publishHouseLabel.setObjectName("publishHouseLabel")
        self.searchFictionbookForm.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.publishHouseLabel)
        self.fictionbookPublishHouse = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.fictionbookPublishHouse.setMinimumSize(QtCore.QSize(0, 25))
        self.fictionbookPublishHouse.setMaximumSize(QtCore.QSize(16777215, 25))
        self.fictionbookPublishHouse.setStyleSheet("background-color: rgb(244, 217, 173);")
        self.fictionbookPublishHouse.setObjectName("fictionbookPublishHouse")
        self.searchFictionbookForm.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.fictionbookPublishHouse)
        self.publishYearLabel = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.publishYearLabel.setFont(font)
        self.publishYearLabel.setStyleSheet("color: rgb(117, 94, 59);")
        self.publishYearLabel.setObjectName("publishYearLabel")
        self.searchFictionbookForm.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.publishYearLabel)
        self.fictionbookPublishYear = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.fictionbookPublishYear.setMinimumSize(QtCore.QSize(0, 25))
        self.fictionbookPublishYear.setMaximumSize(QtCore.QSize(16777215, 25))
        self.fictionbookPublishYear.setStyleSheet("background-color: rgb(244, 217, 173);")
        self.fictionbookPublishYear.setObjectName("fictionbookPublishYear")
        self.searchFictionbookForm.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.fictionbookPublishYear)
        self.inventoryNumberLabel = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.inventoryNumberLabel.setFont(font)
        self.inventoryNumberLabel.setStyleSheet("color: rgb(117, 94, 59);")
        self.inventoryNumberLabel.setObjectName("inventoryNumberLabel")
        self.searchFictionbookForm.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.inventoryNumberLabel)
        self.fictionbookInventoryNumber = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.fictionbookInventoryNumber.setMinimumSize(QtCore.QSize(0, 25))
        self.fictionbookInventoryNumber.setMaximumSize(QtCore.QSize(16777215, 25))
        self.fictionbookInventoryNumber.setStyleSheet("background-color: rgb(244, 217, 173);")
        self.fictionbookInventoryNumber.setObjectName("fictionbookInventoryNumber")
        self.searchFictionbookForm.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.fictionbookInventoryNumber)
        self.countLabel = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.countLabel.setFont(font)
        self.countLabel.setStyleSheet("color: rgb(117, 94, 59);")
        self.countLabel.setObjectName("countLabel")
        self.searchFictionbookForm.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.countLabel)
        self.fictionbookCount = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.fictionbookCount.setMinimumSize(QtCore.QSize(0, 25))
        self.fictionbookCount.setMaximumSize(QtCore.QSize(16777215, 25))
        self.fictionbookCount.setStyleSheet("background-color: rgb(244, 217, 173);")
        self.fictionbookCount.setObjectName("fictionbookCount")
        self.searchFictionbookForm.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.fictionbookCount)
        self.priceLabel = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.priceLabel.setFont(font)
        self.priceLabel.setStyleSheet("color: rgb(117, 94, 59);")
        self.priceLabel.setObjectName("priceLabel")
        self.searchFictionbookForm.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.priceLabel)
        self.fictionbookPrice = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.fictionbookPrice.setMinimumSize(QtCore.QSize(0, 25))
        self.fictionbookPrice.setMaximumSize(QtCore.QSize(16777215, 25))
        self.fictionbookPrice.setStyleSheet("background-color: rgb(244, 217, 173);")
        self.fictionbookPrice.setObjectName("fictionbookPrice")
        self.searchFictionbookForm.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.fictionbookPrice)
        self.invoiceNumLabel = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.invoiceNumLabel.setFont(font)
        self.invoiceNumLabel.setStyleSheet("color: rgb(117, 94, 59);")
        self.invoiceNumLabel.setObjectName("invoiceNumLabel")
        self.searchFictionbookForm.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.invoiceNumLabel)
        self.fictionbookInvoiceNum = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.fictionbookInvoiceNum.setMinimumSize(QtCore.QSize(0, 25))
        self.fictionbookInvoiceNum.setMaximumSize(QtCore.QSize(16777215, 25))
        self.fictionbookInvoiceNum.setStyleSheet("background-color: rgb(244, 217, 173);")
        self.fictionbookInvoiceNum.setObjectName("fictionbookInvoiceNum")
        self.searchFictionbookForm.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.fictionbookInvoiceNum)
        self.invoiceDateLabel = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.invoiceDateLabel.setFont(font)
        self.invoiceDateLabel.setStyleSheet("color: rgb(117, 94, 59);")
        self.invoiceDateLabel.setObjectName("invoiceDateLabel")
        self.searchFictionbookForm.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.invoiceDateLabel)
        self.fictionbookInvoiceDate = QtWidgets.QDateEdit(self.formLayoutWidget)
        self.fictionbookInvoiceDate.setMinimumSize(QtCore.QSize(0, 25))
        self.fictionbookInvoiceDate.setMaximumSize(QtCore.QSize(16777215, 25))
        self.fictionbookInvoiceDate.setStyleSheet("background-color: rgb(244, 217, 173);")
        self.fictionbookInvoiceDate.setDate(QtCore.QDate(1900, 12, 31))
        self.fictionbookInvoiceDate.setObjectName("fictionbookInvoiceDate")
        self.searchFictionbookForm.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.fictionbookInvoiceDate)
        self.sumLabel = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.sumLabel.setFont(font)
        self.sumLabel.setStyleSheet("color: rgb(117, 94, 59);")
        self.sumLabel.setObjectName("sumLabel")
        self.searchFictionbookForm.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.sumLabel)
        self.fictionbookSum = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.fictionbookSum.setMinimumSize(QtCore.QSize(0, 25))
        self.fictionbookSum.setMaximumSize(QtCore.QSize(16777215, 25))
        self.fictionbookSum.setStyleSheet("background-color: rgb(244, 217, 173);")
        self.fictionbookSum.setObjectName("fictionbookSum")
        self.searchFictionbookForm.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.fictionbookSum)
        self.departmentLabel = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.departmentLabel.setFont(font)
        self.departmentLabel.setStyleSheet("color: rgb(117, 94, 59);")
        self.departmentLabel.setObjectName("departmentLabel")
        self.searchFictionbookForm.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.departmentLabel)
        self.fictionbookDepartment = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.fictionbookDepartment.setMinimumSize(QtCore.QSize(0, 25))
        self.fictionbookDepartment.setMaximumSize(QtCore.QSize(16777215, 25))
        self.fictionbookDepartment.setStyleSheet("background-color: rgb(244, 217, 173);")
        self.fictionbookDepartment.setObjectName("fictionbookDepartment")
        self.searchFictionbookForm.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.fictionbookDepartment)
        self.gridLayout.addWidget(self.SearchFictionbookGroupBox, 0, 0, 1, 1)
        self.fictionbookSearchBtn = QtWidgets.QPushButton(SearchFictionbookWindow)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.fictionbookSearchBtn.setFont(font)
        self.fictionbookSearchBtn.setStyleSheet("background-color: rgb(117, 94, 59);\n"
"color: rgb(255, 255, 255);")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icon/icons/searchBtnIcon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.fictionbookSearchBtn.setIcon(icon1)
        self.fictionbookSearchBtn.setCheckable(False)
        self.fictionbookSearchBtn.setObjectName("fictionbookSearchBtn")
        self.gridLayout.addWidget(self.fictionbookSearchBtn, 1, 0, 1, 1)
        self.fictionbookClearBtn = QtWidgets.QPushButton(SearchFictionbookWindow)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.fictionbookClearBtn.setFont(font)
        self.fictionbookClearBtn.setStyleSheet("background-color: rgb(117, 94, 59);\n"
"color: rgb(255, 255, 255);")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icon/icons/clearBtnIcon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.fictionbookClearBtn.setIcon(icon2)
        self.fictionbookClearBtn.setObjectName("fictionbookClearBtn")
        self.gridLayout.addWidget(self.fictionbookClearBtn, 2, 0, 1, 1)
        self.fictionbookCancelBtn = QtWidgets.QPushButton(SearchFictionbookWindow)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.fictionbookCancelBtn.setFont(font)
        self.fictionbookCancelBtn.setStyleSheet("background-color: rgb(117, 94, 59);\n"
"color: rgb(255, 255, 255);")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icon/icons/cancelBtnIcon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.fictionbookCancelBtn.setIcon(icon3)
        self.fictionbookCancelBtn.setObjectName("fictionbookCancelBtn")
        self.gridLayout.addWidget(self.fictionbookCancelBtn, 3, 0, 1, 1)

        self.retranslateUi(SearchFictionbookWindow)
        QtCore.QMetaObject.connectSlotsByName(SearchFictionbookWindow)
        SearchFictionbookWindow.setTabOrder(self.fictionbookAuthor, self.fictionbookTitle)
        SearchFictionbookWindow.setTabOrder(self.fictionbookTitle, self.fictionbookPublishHouse)
        SearchFictionbookWindow.setTabOrder(self.fictionbookPublishHouse, self.fictionbookPublishYear)
        SearchFictionbookWindow.setTabOrder(self.fictionbookPublishYear, self.fictionbookCount)
        SearchFictionbookWindow.setTabOrder(self.fictionbookCount, self.fictionbookPrice)
        SearchFictionbookWindow.setTabOrder(self.fictionbookPrice, self.fictionbookInvoiceNum)

    def retranslateUi(self, SearchFictionbookWindow):
        _translate = QtCore.QCoreApplication.translate
        SearchFictionbookWindow.setWindowTitle(_translate("SearchFictionbookWindow", "Поиск художественной книги"))
        self.SearchFictionbookGroupBox.setTitle(_translate("SearchFictionbookWindow", "Найти художественную книгу"))
        self.authorLabel.setText(_translate("SearchFictionbookWindow", "Автор:"))
        self.titleLabel.setText(_translate("SearchFictionbookWindow", "Название:"))
        self.publishHouseLabel.setText(_translate("SearchFictionbookWindow", "Издательство:"))
        self.publishYearLabel.setText(_translate("SearchFictionbookWindow", "Год издания:"))
        self.inventoryNumberLabel.setText(_translate("SearchFictionbookWindow", "Инвентарный номер:"))
        self.countLabel.setText(_translate("SearchFictionbookWindow", "Количество:"))
        self.priceLabel.setText(_translate("SearchFictionbookWindow", "Цена:"))
        self.invoiceNumLabel.setText(_translate("SearchFictionbookWindow", "№ накладной:"))
        self.invoiceDateLabel.setText(_translate("SearchFictionbookWindow", "Дата накладной"))
        self.fictionbookInvoiceDate.setDisplayFormat(_translate("SearchFictionbookWindow", "dd.MM.yyyy"))
        self.sumLabel.setText(_translate("SearchFictionbookWindow", "Сумма:"))
        self.departmentLabel.setText(_translate("SearchFictionbookWindow", "Отдел:"))
        self.fictionbookSearchBtn.setText(_translate("SearchFictionbookWindow", "Найти"))
        self.fictionbookClearBtn.setText(_translate("SearchFictionbookWindow", "Сбросить"))
        self.fictionbookCancelBtn.setText(_translate("SearchFictionbookWindow", "Отмена"))

import package.views.images_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SearchFictionbookWindow = QtWidgets.QDialog()
    ui = Ui_SearchFictionbookWindow()
    ui.setupUi(SearchFictionbookWindow)
    SearchFictionbookWindow.show()
    sys.exit(app.exec_())

